
spring:
  application:
    name: exchange rate
  data:
    rest:
      base-path: /api
      default-page-size: 20
  datasource:
    username: root
    password:
    url: jdbc:mysql://localhost:3307/rate_exchange
  jpa:
    database-platform: 'null'
#    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
        use_sql_comments: true
#    show-sql: true
    generate-ddl: true
